[build]
# CÃ i Tesseract + OpenCV dependencies
postinstall = """
apt-get update && \
apt-get install -y tesseract-ocr libgl1-mesa-glx libglib2.0-0 && \
pip install -r requirements.txt
"""

[service]
start = "gunicorn split:app"
